services:
  frontend:
    image: next
    build:
      context: ../frontend
      dockerfile: ../dev-config/Dockerfile.frontend
    ports:
      - "3000:3000"
    volumes:
      - ../frontend:/app
      - /app/node_modules
      - /app/.next
    environment:
      API_TOKEN: ${API_TOKEN}
      API_URL: ${API_URL}
    networks:
      - strapi
  cms:
    image: strapi
    container_name: cms
    build:
      context: ../cms
      dockerfile: ../dev-config/Dockerfile.cms
    ports:
      - "1337:1337"
    volumes:
      - ../cms:/app
      - /app/node_modules
      - ../cms/package.json:/app/package.json
    # volumes:
    #   - ../cms/config:/usr/app/config
    #   - ../cms/src:/usr/app/src
    #   - ../cms/package.json:/usr/app/package.json
    #   - ../cms/package-lock.json:/usr/app/package-lock.json
    #   - ../cms/public/uploads:/usr/app/public/uploads
    environment:
      APP_KEYS: ${APP_KEYS}
      API_TOKEN_SALT: ${API_TOKEN_SALT}
      ADMIN_JWT_SECRET: ${ADMIN_JWT_SECRET}
      TRANSFER_TOKEN_SALT: ${TRANSFER_TOKEN_SALT}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_HOST: db
      DATABASE_CLIENT: postgres
      DATABASE_PORT: 5432
      DATABASE_SSL: "false"
      NODE_ENV: ${NODE_ENV}
      CMS_URL: ${CMS_URL}
    networks:
      - strapi
  db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_DB: ${DATABASE_NAME}
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      - strapi

  nginx:
    image: nginx
    container_name: nginx
    ports:
      - "80:80"
    environment:
      NGINX_DOMAIN: ${NGINX_DOMAIN}
    volumes:
      - ./nginx/config/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - strapi
    restart: always
networks:
  strapi:
volumes:
  db:
