FROM node:latest

WORKDIR /app

COPY package*.json ./

RUN npm ci

COPY . .

ENV NODE_ENV=${NODE_ENV}
ENV API_URL=${API_URL}
ENV API_TOKEN=${API_TOKEN}


RUN npm run build

CMD ["npm", "run", "start"]