services:
  frontend:
    image: dev-config-frontend
    ports:
      - "3000:3000"
    environment:
      API_TOKEN: ${API_TOKEN}
      API_URL: ${API_URL}
    networks:
      - strapi
  cms:
    container_name: cms
    ports:
      - "1337:1337"
    environment:
      APP_KEYS: ${APP_KEYS}
      API_TOKEN_SALT: ${API_TOKEN_SALT}
      ADMIN_JWT_SECRET: ${ADMIN_JWT_SECRET}
      TRANSFER_TOKEN_SALT: ${TRANSFER_TOKEN_SALT}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_HOST: db
      DATABASE_CLIENT: postgres
      DATABASE_PORT: 5432
      DATABASE_SSL: "false"
      NODE_ENV: ${NODE_ENV}
      CMS_URL: ${CMS_URL}
    networks:
      - strapi
  db:
    image: postgres:16.3-alpine
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_DB: ${DATABASE_NAME}
    volumes:
      - db_pub:/var/lib/postgresql/data
    networks:
      - strapi

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    environment:
      NGINX_DOMAIN: ${NGINX_DOMAIN}
    volumes:
      - ./nginx/config/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - strapi
    restart: always
networks:
  strapi:
volumes:
  db_pub:
